spring.application.name=usuarios

# Configuración de la DB (MariaDB/MySQL)
# 1. Conexión estándar
spring.datasource.url=jdbc:mariadb://localhost:3306/antuco_usuarios_db
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
