spring.application.name=usuarios

# Configuración de la DB (MariaDB/MySQL)
# 1. Conexión estándar
spring.datasource.url=jdbc:mysql://localhost:3306/antuco_usuarios_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

Spring.flyway.enabled=true
Spring.flyway.repeatable-sql-migration-prefix=true