spring.application.name:catalogo


spring.datasource.url=jdbc:mysql://localhost:3306/catalogo_db
spring.datasource.username=root
spring.datasource.password=
#create-drop me servira para formatear una tabla la cual este mal hecha
spring.jpa.show-sql=true

server.error.include-message=always