spring.datasource.url=jdbc:mariadb://localhost:3306/carrito_bd
spring.datasource.username=myadmin
spring.datasource.password=821721
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#> CREATE DATABASE <nombre>;
#> GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
#> FLUSH PRIVILEGES;
#> EXIT;
